spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taskdb
    username: root
    password: w2412012
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true